"""telemetry idempotency constraint

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 21:49:48.324999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_telemetry_reading', 'telemetry', ['tenant_id', 'asset_id', 'metric', 'event_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_telemetry_reading', 'telemetry', type_='unique')
    # ### end Alembic commands ###
