"""initial canonical schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 21:30:35.099918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('deployment_mode', sa.String(length=20), nullable=False),
    sa.Column('data_residency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('market_area', sa.String(length=20), nullable=False),
    sa.Column('units', sa.String(length=10), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('quotas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('actor_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_pointer', sa.String(length=300), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_time', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_table('constraints',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('constraint_type', sa.String(length=60), nullable=False),
    sa.Column('expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_hard', sa.Boolean(), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraints_tenant_id'), 'constraints', ['tenant_id'], unique=False)
    op.create_table('objective_policies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('carbon_price_per_tonne', sa.Float(), nullable=False),
    sa.Column('risk_aversion', sa.Float(), nullable=False),
    sa.Column('combination_method', sa.String(length=60), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_policies_tenant_id'), 'objective_policies', ['tenant_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_tenant_id'), 'portfolios', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('credential_refs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('auth_type', sa.String(length=30), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_refs_tenant_id'), 'credential_refs', ['tenant_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('portfolio_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('decision_cycle_id', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=60), nullable=False),
    sa.Column('horizon', sa.String(length=10), nullable=False),
    sa.Column('autonomy_mode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trusted_snapshot_ref', sa.String(length=120), nullable=True),
    sa.Column('forecast_bundle_ref', sa.String(length=120), nullable=True),
    sa.Column('scenario_set_ref', sa.String(length=120), nullable=True),
    sa.Column('objective_policy_version', sa.Integer(), nullable=True),
    sa.Column('constraint_set_ref', sa.String(length=120), nullable=True),
    sa.Column('optimisation_run_id', sa.String(length=120), nullable=True),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('binding_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'decision_cycle_id', 'version', name='uq_decision_cycle_version')
    )
    op.create_index(op.f('ix_decisions_decision_cycle_id'), 'decisions', ['decision_cycle_id'], unique=False)
    op.create_index(op.f('ix_decisions_portfolio_id'), 'decisions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_decisions_tenant_id'), 'decisions', ['tenant_id'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requested_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('object_key', sa.String(length=300), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_tenant_id'), 'export_jobs', ['tenant_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('portfolio_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('grid_connection_point', sa.String(length=120), nullable=True),
    sa.Column('market_area', sa.String(length=20), nullable=False),
    sa.Column('topology', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_portfolio_id'), 'sites', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('site_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('rated_capacity_kw', sa.Float(), nullable=False),
    sa.Column('ramp_rate_kw_per_min', sa.Float(), nullable=True),
    sa.Column('capability_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('control_endpoint_ref', sa.String(length=120), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_site_id'), 'assets', ['site_id'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_ref_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('schema_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('approval_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('activated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_test_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['credential_ref_id'], ['credential_refs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_tenant_id'), 'connectors', ['tenant_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('decision_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expected_outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_asset_id'), 'actions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_actions_decision_id'), 'actions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_actions_tenant_id'), 'actions', ['tenant_id'], unique=False)
    op.create_table('batteries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('energy_capacity_kwh', sa.Float(), nullable=False),
    sa.Column('power_limit_kw', sa.Float(), nullable=False),
    sa.Column('soc_min_pct', sa.Float(), nullable=False),
    sa.Column('soc_max_pct', sa.Float(), nullable=False),
    sa.Column('soc_current_pct', sa.Float(), nullable=False),
    sa.Column('soh_pct', sa.Float(), nullable=False),
    sa.Column('round_trip_efficiency', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('degradation_cost_per_kwh_cycled', sa.Float(), nullable=False),
    sa.Column('warranty_cycles_remaining', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batteries_asset_id'), 'batteries', ['asset_id'], unique=True)
    op.create_index(op.f('ix_batteries_tenant_id'), 'batteries', ['tenant_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('site_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('variable', sa.String(length=40), nullable=False),
    sa.Column('issue_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantile', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id', 'valid_time')
    )
    op.create_index(op.f('ix_forecasts_asset_id'), 'forecasts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_forecasts_issue_time'), 'forecasts', ['issue_time'], unique=False)
    op.create_index(op.f('ix_forecasts_site_id'), 'forecasts', ['site_id'], unique=False)
    op.create_index(op.f('ix_forecasts_tenant_id'), 'forecasts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_forecasts_valid_time'), 'forecasts', ['valid_time'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingest_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id', 'event_time')
    )
    op.create_index(op.f('ix_telemetry_asset_id'), 'telemetry', ['asset_id'], unique=False)
    op.create_index('ix_telemetry_asset_metric_time', 'telemetry', ['asset_id', 'metric', 'event_time'], unique=False)
    op.create_index(op.f('ix_telemetry_event_time'), 'telemetry', ['event_time'], unique=False)
    op.create_index(op.f('ix_telemetry_metric'), 'telemetry', ['metric'], unique=False)
    op.create_index(op.f('ix_telemetry_tenant_id'), 'telemetry', ['tenant_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('decision_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('approver_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('modified_bounds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requires_second_approver', sa.Boolean(), nullable=False),
    sa.Column('second_approver_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['second_approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_approvals_action_id'), 'approvals', ['action_id'], unique=False)
    op.create_index(op.f('ix_approvals_decision_id'), 'approvals', ['decision_id'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('correlation_id', sa.String(length=80), nullable=False),
    sa.Column('decision_version', sa.Integer(), nullable=False),
    sa.Column('target_asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('command_type', sa.String(length=40), nullable=False),
    sa.Column('setpoint_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('validity_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validity_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('safety_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('approval_ref', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('state_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_signals_action_id'), 'signals', ['action_id'], unique=False)
    op.create_index(op.f('ix_signals_correlation_id'), 'signals', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_signals_tenant_id'), 'signals', ['tenant_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('signal_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('adapter', sa.String(length=40), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('prepare_status', sa.String(length=20), nullable=False),
    sa.Column('commit_status', sa.String(length=20), nullable=False),
    sa.Column('ack_status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_signal_id'), 'commands', ['signal_id'], unique=False)
    op.create_index(op.f('ix_commands_tenant_id'), 'commands', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commands_tenant_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_signal_id'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_signals_tenant_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_correlation_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_action_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_decision_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_action_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_telemetry_tenant_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_metric'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_event_time'), table_name='telemetry')
    op.drop_index('ix_telemetry_asset_metric_time', table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_asset_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_forecasts_valid_time'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_tenant_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_site_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_issue_time'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_asset_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_batteries_tenant_id'), table_name='batteries')
    op.drop_index(op.f('ix_batteries_asset_id'), table_name='batteries')
    op.drop_table('batteries')
    op.drop_index(op.f('ix_actions_tenant_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_decision_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_asset_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_connectors_tenant_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_site_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_portfolio_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_export_jobs_tenant_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_decisions_tenant_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_portfolio_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision_cycle_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_credential_refs_tenant_id'), table_name='credential_refs')
    op.drop_table('credential_refs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_portfolios_tenant_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_objective_policies_tenant_id'), table_name='objective_policies')
    op.drop_table('objective_policies')
    op.drop_index(op.f('ix_constraints_tenant_id'), table_name='constraints')
    op.drop_table('constraints')
    op.drop_index('ix_audit_tenant_time', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
