"""autonomy policy table

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-24 22:15:52.841642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autonomy_policies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('max_action_risk', sa.String(length=20), nullable=False),
    sa.Column('safety_case_ref', sa.String(length=200), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('set_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autonomy_policies_scope'), 'autonomy_policies', ['scope'], unique=False)
    op.create_index(op.f('ix_autonomy_policies_tenant_id'), 'autonomy_policies', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autonomy_policies_tenant_id'), table_name='autonomy_policies')
    op.drop_index(op.f('ix_autonomy_policies_scope'), table_name='autonomy_policies')
    op.drop_table('autonomy_policies')
    # ### end Alembic commands ###
