"""scenario runs table

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-25 08:30:08.044824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('decision_cycle_id', sa.String(length=80), nullable=False),
    sa.Column('scenario_name', sa.String(length=40), nullable=False),
    sa.Column('solver_status', sa.String(length=20), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=False),
    sa.Column('delta_vs_baseline', sa.Float(), nullable=True),
    sa.Column('total_import_kwh', sa.Float(), nullable=False),
    sa.Column('total_export_kwh', sa.Float(), nullable=False),
    sa.Column('total_curtailment_kwh', sa.Float(), nullable=False),
    sa.Column('total_shed_kwh', sa.Float(), nullable=False),
    sa.Column('binding_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_runs_decision_cycle_id'), 'scenario_runs', ['decision_cycle_id'], unique=False)
    op.create_index('ix_scenario_runs_tenant_cycle', 'scenario_runs', ['tenant_id', 'decision_cycle_id'], unique=False)
    op.create_index(op.f('ix_scenario_runs_tenant_id'), 'scenario_runs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_runs_tenant_id'), table_name='scenario_runs')
    op.drop_index('ix_scenario_runs_tenant_cycle', table_name='scenario_runs')
    op.drop_index(op.f('ix_scenario_runs_decision_cycle_id'), table_name='scenario_runs')
    op.drop_table('scenario_runs')
    # ### end Alembic commands ###
