"""document intakes table

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25 09:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_intakes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('affected_asset_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('capacity_impact_pct', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_excerpt', sa.Text(), nullable=False),
    sa.Column('model_provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('constraint_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('applied_by', sa.String(length=200), nullable=True),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['constraint_id'], ['constraints.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_intakes_checksum'), 'document_intakes', ['checksum'], unique=False)
    op.create_index('ix_document_intakes_tenant_created', 'document_intakes', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_document_intakes_tenant_id'), 'document_intakes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_intakes_tenant_id'), table_name='document_intakes')
    op.drop_index('ix_document_intakes_tenant_created', table_name='document_intakes')
    op.drop_index(op.f('ix_document_intakes_checksum'), table_name='document_intakes')
    op.drop_table('document_intakes')
    # ### end Alembic commands ###
